{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "walrus.secretName" . }}
  labels:
    {{- include "walrus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.passwordKey }}: {{ .Values.secret.pgPassword | quote }}
{{- end }}
